apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: elasticsearch
  namespace: kube-system 
spec:
 replicas: 2
 template:
   metadata:
     labels:
       system: ReplicaOne
   spec:
     containers:
      - name: elasticsearch  
        image: k8s.gcr.io/fluentd-elasticsearch:1.20 
