apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: elephant
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 50M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 100Mi
      requests:
        memory: 50Mi
